export interface ReviewEntry extends Record<string, unknown> {
  id: number;
  employee: string;
  service: string;
  amount: number;
  tip: number;
  date: string;
  time: string;
  status: "Approved" | "Rejected" | "Pending";
}

export const reviewEntriesData: ReviewEntry[] = [
  {
    id: 1,
    employee: "Sarah Johnson",
    service: "Haircut & Color",
    amount: 85.0,
    tip: 15.0,
    date: "2024-05-10",
    time: "10:30 AM",
    status: "Approved",
  },
  {
    id: 2,
    employee: "Emily Rodriguez",
    service: "Manicure",
    amount: 25.0,
    tip: 5.0,
    date: "2024-05-10",
    time: "11:00 AM",
    status: "Pending",
  },
  {
    id: 3,
    employee: "Mike Chen",
    service: "Facial Treatment",
    amount: 65.0,
    tip: 12.0,
    date: "2024-05-10",
    time: "2:15 PM",
    status: "Approved",
  },
  {
    id: 4,
    employee: "Jessica Lee",
    service: "Hair Styling",
    amount: 45.0,
    tip: 8.0,
    date: "2024-05-09",
    time: "3:30 PM",
    status: "Rejected",
  },
  {
    id: 5,
    employee: "David Park",
    service: "Beard Trim",
    amount: 20.0,
    tip: 4.0,
    date: "2024-05-09",
    time: "4:00 PM",
    status: "Approved",
  },
  {
    id: 6,
    employee: "Sarah Johnson",
    service: "Pedicure",
    amount: 35.0,
    tip: 6.0,
    date: "2024-05-09",
    time: "1:45 PM",
    status: "Pending",
  },
  {
    id: 7,
    employee: "Emily Rodriguez",
    service: "Waxing",
    amount: 40.0,
    tip: 7.0,
    date: "2024-05-08",
    time: "2:00 PM",
    status: "Approved",
  },
  {
    id: 8,
    employee: "Mike Chen",
    service: "Massage",
    amount: 55.0,
    tip: 10.0,
    date: "2024-05-08",
    time: "10:15 AM",
    status: "Pending",
  },
  {
    id: 9,
    employee: "Jessica Lee",
    service: "Haircut",
    amount: 30.0,
    tip: 5.0,
    date: "2024-05-08",
    time: "11:30 AM",
    status: "Approved",
  },
  {
    id: 10,
    employee: "David Park",
    service: "Eyebrow Design",
    amount: 15.0,
    tip: 3.0,
    date: "2024-05-07",
    time: "3:15 PM",
    status: "Rejected",
  },
  {
    id: 11,
    employee: "Sarah Johnson",
    service: "Haircut & Color",
    amount: 85.0,
    tip: 15.0,
    date: "2024-05-10",
    time: "10:30 AM",
    status: "Approved",
  },
  {
    id: 12,
    employee: "Emily Rodriguez",
    service: "Manicure",
    amount: 25.0,
    tip: 5.0,
    date: "2024-05-10",
    time: "11:00 AM",
    status: "Pending",
  },
  {
    id: 13,
    employee: "Mike Chen",
    service: "Facial Treatment",
    amount: 65.0,
    tip: 12.0,
    date: "2024-05-10",
    time: "2:15 PM",
    status: "Approved",
  },
  {
    id: 14,
    employee: "Jessica Lee",
    service: "Hair Styling",
    amount: 45.0,
    tip: 8.0,
    date: "2024-05-09",
    time: "3:30 PM",
    status: "Rejected",
  },
  {
    id: 15,
    employee: "David Park",
    service: "Beard Trim",
    amount: 20.0,
    tip: 4.0,
    date: "2024-05-09",
    time: "4:00 PM",
    status: "Approved",
  },
  {
    id: 16,
    employee: "Sarah Johnson",
    service: "Pedicure",
    amount: 35.0,
    tip: 6.0,
    date: "2024-05-09",
    time: "1:45 PM",
    status: "Pending",
  },
  {
    id: 17,
    employee: "Emily Rodriguez",
    service: "Waxing",
    amount: 40.0,
    tip: 7.0,
    date: "2024-05-08",
    time: "2:00 PM",
    status: "Approved",
  },
  {
    id: 18,
    employee: "Mike Chen",
    service: "Massage",
    amount: 55.0,
    tip: 10.0,
    date: "2024-05-08",
    time: "10:15 AM",
    status: "Pending",
  },
  {
    id: 19,
    employee: "Jessica Lee",
    service: "Haircut",
    amount: 30.0,
    tip: 5.0,
    date: "2024-05-08",
    time: "11:30 AM",
    status: "Approved",
  },
  {
    id: 20,
    employee: "David Park",
    service: "Eyebrow Design",
    amount: 15.0,
    tip: 3.0,
    date: "2024-05-07",
    time: "3:15 PM",
    status: "Rejected",
  },
];
